print(4+3)
print(4-3)
print(4*3)
print(4%3)
print(4/3)
print(4**3)
print(4//3)
print(str("Andrey"))
print(str("Anrango"))
print(str("Ecuador"))
print(str("Estoy disfrutando de estos 30 días de Python"))
print (type(10))
print (type(9.8))
print (type(['Asabeneh', 'Python', 'Finland']))
print (type("Anrango"))
print (type("Ecuador"))
